### PR TITLE
bump clearpath_socketcan_interface to C++17 to solve std::filesystem not declared error.

### PR DESCRIPTION
**Pull request by Mechazo11**
Solves #21

### CODE REVIEW

**Comment by tonybaltovski** [comment]
Thank you for this PR.  At the moment, we are working on Jazzy updates and clearpath_socketcan_interface will be removed.  Thus, I am closing this PR.

**Comment by Mechazo11** [comment]
@tonybaltovski thank you very much for letting me know. If you do end up discontinuing ```clearpath_socketcan_interface``` can you kindly drop a note in this PR or the Issue #21.

With best regards,
@Mechazo11

**Comment by Mechazo11** [comment]
Hi @tonybaltovski sorry for posting on a closed issue.  I have had some success in forward porting clearpath_simulator to Gazebo Harmonic but have a number of questions. Would you suggest a mode of communication i.e. opening Issues in [clearpath_simulator](https://github.com/clearpathrobotics/clearpath_simulator/), email, LinkedIn?

With best,
@Mechazo11

**Comment by tonybaltovski** [comment]
Hi @Mechazo11, opening issues on the repo is ideal.

**Pull request closed without merging**
